[package]
name = "https-from-scratch"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
bytes = "1.0"
rustls = "0.23.22"
webpki-roots = "0.26.8"

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }
bytes = "1.0"
